apiVersion: batch/v1
kind: CronJob
metadata:
  name: awscli
  namespace: goalapp
spec:
  schedule: "30 20 * * *"  # Everyday 2.30 AM in IST
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: s3pushaccount
          containers:
          - name: s3-push-job
            image: amazon/aws-cli:latest
            volumeMounts:
            - name: backups
              mountPath: ~/backups
            command:
            - s3 sync ~/backups s3://mongoproject/backups --delete
          restartPolicy: OnFailure
          volumes:
          - name: backups
            persistentVolumeClaim:
              claimName: cron-pvc


# docker run --rm -it -v ~/.aws:/root/.aws -v ~/mongodb:/root/mongodb --name aws amazon/aws-cli s3 sync ~/mongodb s3://dupmongotest/mongodb --delete