apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goal-jenkins-sc
  labels:
     for: mongodb
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: 
  directoryPerms: "755"
  uid: "1000"
  gid: "1000"