apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3pushaccount
  namespace: goalapp
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::549825371516:role/s3-push"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3pushrole
  namespace: goalapp
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "use", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3pushrolebinding
  namespace: goalapp
subjects:
  - kind: ServiceAccount
    name: s3pushaccount
roleRef:
  - kind: Role
    name: s3pushrole
    apiGroup: rbac.authorization.k8s.io