apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goal-sc
  labels:
     for: goalapp
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: 
  directoryPerms: "700"