apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goal-sc
  labels:
     for: goalapp
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: 
  directoryPerms: "700"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cron-pvc
  namespace: goalapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi