apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goal-mongo-sc
  labels:
     for: mongodb
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "fs-041ad3df07469889f"
  directoryPerms: "755"
  posixUser: "999"
  posixGroup: "999"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cron-pvc
  namespace: goalapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: goal-mongo-sc
  resources:
    requests:
      storage: 1Gi