name: 'Terraform destroy for the infrastructure.'

on:                     # Triggers which execute the script.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:     # This is to allow users to manually run the script in Actions
permissions:
  contents: read

jobs:
  spin_vpc:
  # If condition specifying the keyword in commit msg which should perform this script.
    if: ${{ success() && contains(github.event.head_commit.message, 'terraform_destroy') || contains(github.event.head_commit.message, 'terraform_destroy_all') }}
    runs-on: ubuntu-latest      # runner on which the script should be executed.
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.secret_access_key }}
          aws-region: ap-southeast-1
      - name: 'Run Terraform destroy to bring down all the resources.'
        run: |
          cd ../terraform/terraform-eks/
          echo "initialising terraform..."
          terraform init || terraform init --reconfigure
          echo "Destroying all the resources..."
          terraform destroy -auto-approve 
          sleep 120
          cd ../terraform-vpc/
          echo "Destroying the VPC..."
          terraform destroy -auto-approve