name: Terraform destroy for the infrastructure.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  spin_vpc:
    if: ${{ success() && contains(github.event.head_commit.message, 'terraform_destroy') || contains(github.event.head_commit.message, 'terraform_destroy_all') }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.secret_access_key }}
          aws-region: ap-southeast-1
      - name: Run Terraform destroy to bring down all the resources.
        run: |
          cd ../terraform/terraform-eks/
          echo "initialising terraform..."
          terraform init || terraform init --reconfigure
          echo "Destroying all the resources..."
          terraform destroy -auto-approve
          sleep 120
          cd ../terraform-vpc/
          echo "Destroying the VPC..."
          terraform destroy -auto-approve